In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random
from random import seed
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

from keras.utils.vis_utils import plot_model
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import tree

Using TensorFlow backend.


In [2]:
dataset = pd.read_csv("train.csv")

features = dataset.iloc[:, 5:15].values
print(features.shape)

labels = dataset.iloc[:, 15].values
print(labels.shape)
#print(labels)

print(features)

(451, 10)
(451,)
[[  8   6  12 ...  73   0   0]
 [ 14 141   8 ... 115   0   1]
 [  9   0   7 ...  26   0   0]
 ...
 [  8 149  17 ... 551   0   1]
 [ 14   0   6 ...   2   0   0]
 [ 10   0   5 ...   3   0   0]]


In [3]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.2, random_state= 2255)
print(features_train.shape)
print(features_train)


(360, 10)
[[  12    0    5 ...    1    0    0]
 [   6    0    7 ... 5989    4    0]
 [  10   36   10 ...   53    0    0]
 ...
 [  11    0    0 ...    4    0    0]
 [  11    0    5 ...   22    0    0]
 [   7    0    0 ...    0    0    0]]


In [4]:
clf = DecisionTreeClassifier(criterion='entropy', min_samples_split=50)
clf.fit(features_train, labels_train)


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=50,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [5]:
y_pred =  clf.predict(features_test)

In [6]:
print('Accuracy Score on train data: ', accuracy_score(y_true=labels_train, y_pred=clf.predict(features_train)))
print('Accuracy Score on test data: ', accuracy_score(y_true=labels_test, y_pred=y_pred))


Accuracy Score on train data:  0.9111111111111111
Accuracy Score on test data:  0.9120879120879121


In [7]:
validation_set = pd.read_csv("test.csv")

validation_features = validation_set.iloc[:, 5:15].values
print(validation_features.shape)

validation_labels = validation_set.iloc[:, 15].values
print(validation_labels.shape)


(518, 10)
(518,)


In [11]:
y_pred =  clf.predict(validation_features)
print('Accuracy Score on validation data: ', accuracy_score(y_true=validation_labels, y_pred=y_pred))

Accuracy Score on validation data:  0.8783783783783784


In [9]:
print(classification_report(validation_labels, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.76      0.83       200
           1       0.86      0.96      0.91       318

    accuracy                           0.88       518
   macro avg       0.89      0.86      0.87       518
weighted avg       0.88      0.88      0.88       518



In [10]:
print(confusion_matrix(validation_labels, y_pred))

[[151  49]
 [ 14 304]]
